mod common;
use common::*;

#[derive(Debug)]
struct Example(&'static str);

fn ok(q: &str) {
    let _ = parse_ok(q);
}

#[test]
fn all_examples_parse() {
    // A wide set of examples akin to user manual coverage.
    let cases = vec![
        Example("reports"),
        Example("D:"),
        Example(r"D:\\Downloads\\"),
        Example(r#""C:\\Program Files\\""#),
        Example(r"documents\\"),
        Example(r#""summer holiday""#),
        Example("foo bar"),
        Example("foo|bar"),
        Example("!temp"),
        Example("<D: | E:> *.mp3"),
        Example(r#""Program Files""#),
        Example("foo AND bar"),
        Example("NOT temp"),
        Example("*.mp3"),
        Example("report-??.txt"),
        Example("a*b"),
        Example("file: 报告"),
        Example("folder: 项目"),
        Example("ext:txt;doc;docx"),
        Example("type:picture"),
        Example("type:video"),
        Example("type:document"),
        Example("audio:"),
        Example("video:"),
        Example("doc:"),
        Example("exe:"),
        Example("size:>1GB"),
        Example("dm:today"),
        Example("dc:thisweek"),
        Example("dc:2023-01-01..2023-12-31"),
        Example("tag:Project"),
        Example(r"parent:C:\\Windows"),
        Example(r"D:\\Music\\"),
        Example(r"D:\\Music\\ !child:*.mp3"),
        Example("attrib:H"),
        Example("attrib:R"),
        Example("dimensions:1920x1080"),
        Example("width:>4000"),
        Example("dupe: *.mp4"),
        Example("size:>1gb sizedupe:"),
        Example("folder: dm:pastmonth ext:docx report"),
        Example(r"regex:^Report.*2025$"),
        Example(r"regex:^(?i)Readme\."),
        Example(r"regex:[0-9]{4}"),
        Example(r"regex:\.jpe?g$"),
        Example(r"regex:error"),
        Example("*.log"),
        Example("ABC 123"),
        Example("ABC|123"),
        Example("case:ABC"),
        Example("D:|E: *.mp3"),
        Example("D: *.jpg|*.png"),
        Example("!."),
        Example("file:"),
        Example("folder:"),
        Example("size:>1mb"),
        Example("size:1mb..10mb"),
        Example("dm:today"),
        Example("dc:thisweek"),
        Example("dc:1/8/2014-31/8/2014"),
        Example("dc:2014/8/1-2014/8/31"),
        Example(r"D:\\music\\ !child:*.mp3"),
        Example(r"regex:[^\x00-\x7f]"),
        Example("video: size:>1gb"),
        Example("audio: year:2024"),
        Example("musiclastyear:"),
        Example("%TEMP%\\*.log"),
        Example("ext:pdf report"),
        Example("Pictures vacation"),
        Example("report ext:docx"),
        // Additional coverage below to push breadth and ensure more shapes.
        Example("artist:Daft"),
        Example("album:Discovery"),
        Example("title:OneMoreTime"),
        Example("genre:house"),
        Example("year:2024"),
        Example("track:01"),
        Example("comment:live"),
        Example("height:<=2000"),
        Example("orientation:horizontal"),
        Example("bitdepth:24"),
        Example("attrib:S"),
        Example("attrib:A"),
        Example("attrib:HS"),
        Example("content:panic"),
        Example("parent:/Users"),
        Example("infolder:/Users/demo"),
        Example("nosubfolders:/Users/demo"),
        Example("child:*.jpg"),
        Example("namepartdupe:"),
        Example("sizedupe:"),
        Example("attribdupe:"),
        Example("dmdupe:"),
        Example("dupe:"),
        Example("ext:jpg;png;gif;bmp;webp"),
        Example("ext:7z;zip;tar;gz"),
        Example("ext:mp3;flac;mp4;avi;mkv"),
        Example("size:<10mb"),
        Example("size:>=1024"),
        Example("size:=2048"),
        Example("size:!=4096"),
        Example("dc:2020/01/01-2020/12/31"),
        Example("dm:2021/05/01-2021/06/01"),
        Example("da:2022/01/01-2022/02/01"),
        Example("dr:2023/03/01-2023/04/01"),
        Example("dc:2020-01-01..2020-12-31"),
        Example("da:..2022/12/31"),
        Example("dr:2021/01/01.."),
        Example("dimensions:1024x768"),
        Example("width:4096"),
        Example("height:2160"),
        Example("type:archive"),
        Example("type:compressed"),
        Example("type:source"),
        Example("type:executable"),
        Example("foo AND "),
        Example(" AND bar"),
        Example(" | "),
        Example("||"),
        Example(" | foo | "),
        Example("   "),
        Example("NOT   temp"),
        Example("!!!foo"),
        Example("(foo bar) baz"),
        Example("<foo|bar>"),
        Example("(<a b> c) d"),
        Example("<D: | E:> *.mp3|*.wav"),
        Example("D:|E: *.mp3"),
        Example("D: *.jpg|*.png"),
        Example("regex:  ^Readme\\.md$"),
    ];

    for Example(q) in cases {
        ok(q);
    }
}
